# const searchString = "lap";
# const pageIndex = 1; 
# const pageSize = 10; 

# post http://localhost:3001/api/upload/delete/1700057802961logo-dell.png


# post http://localhost:3001/api/SendEmail/send
# Content-Type: application/json
# Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBoYW12YW5jdWEiLCJlbWFpbCI6InBoYW1jdWE2NzBAZ21haWwuY29tIiwicGFzc3dvcmQiOiJwYXNzd29yZDEiLCJoaWRkZW4iOjAsInJvbGVzIjoiVXNlciIsImlhdCI6MTY5OTk0NTk1NywiZXhwIjoxNzAwMDMyMzU3fQ.jYeV4Y_lOqL9jD9J7ednok8nHd7fMDd6aCEvMpVzT_I



Get http://localhost:3001/api/product/getAll?searchString=l
&pageIndex=1&pageSize=1
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo2LCJ1c2VybmFtZSI6InBoYW12YW5jdWEiLCJlbWFpbCI6InBoYW1jdWE2NzBAZ21haWwuY29tIiwicGFzc3dvcmQiOiJwYXNzd29yZDEiLCJoaWRkZW4iOjAsInJvbGVzIjoiVXNlciIsImlhdCI6MTcwMTY3NjAwOCwiZXhwIjoxNzAxNzYyNDA4fQ.Ss7eI2OukwjFZC_SwfT_wrCJBnUsDqPX-hF7x9oz4p0
# GET http://localhost:3001/api/user/getAll?searchString=user5&pageIndex=1&pageSize=5
# Content-Type: application/json


# POST http://localhost:3001/api/user/login
# Content-Type: application/json

# {
#     "email":"phamcua670@gmail.com",
#     "password":"password1"
# }

# POST http://localhost:3001/api/user/register
# Content-Type: application/json

# {
#     "username":"phamvancua223",
#     "email" :"phamcua670@gmail223.com",
#     "password":"password1",
#     "phone_number":"12345"
# }